# Generated by Django 2.1.2 on 2018-11-19 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afirmacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regla', models.CharField(max_length=50)),
                ('reglaPosIzq', models.IntegerField(blank=True, null=True, verbose_name='Posicion izquierda de regla aplicada')),
                ('reglaPosDer', models.IntegerField(blank=True, null=True, verbose_name='Posicion derecha de regla aplicada')),
                ('deduccionNueva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inferencias_anteriores', to='pruebas.Deduccion')),
                ('deduccionVieja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inferencias_posteriores', to='pruebas.Deduccion')),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('afirmacion', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de la Prueba')),
            ],
        ),
        migrations.AddField(
            model_name='inferencia',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inferencias', to='pruebas.Prueba'),
        ),
        migrations.AddField(
            model_name='deduccion',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deducciones', to='pruebas.Prueba'),
        ),
        migrations.AlterUniqueTogether(
            name='inferencia',
            unique_together={('prueba', 'deduccionVieja', 'deduccionNueva')},
        ),
        migrations.AlterUniqueTogether(
            name='deduccion',
            unique_together={('afirmacion', 'prueba')},
        ),
    ]
